### PR TITLE
Story/vethub 95

### PR DESCRIPTION
**Pull request by Jo-Zh**
Implement QuestionStack Algo function to show pre and next questions and updated quizStats (to track quiz status during timed mode.)
to test:
`yarn test`

### CODE REVIEW

**Review by Mohamad11Dab — COMMENTED** [review]
Everything appears to be in order. However, I've noticed that when the user navigates back to a previous question, the selected answer isn't highlighted. Is this how it's supposed to function? Additionally, how does a student know they've reached the last question? Perhaps this issue should be addressed in a separate ticket, but maybe we could add a submit button on the final question to indicate it's the end?

**Review by Mohamad11Dab — COMMENTED** [review]
Also the skip button in the tutor mode is not functional... do we need it ?

**Comment by Jo-Zh** [comment]
> Everything appears to be in order. However, I've noticed that when the user navigates back to a previous question, the selected answer isn't highlighted. Is this how it's supposed to function? Additionally, how does a student know they've reached the last question? Perhaps this issue should be addressed in a separate ticket, but maybe we could add a submit button on the final question to indicate it's the end?

Yes, this function will be in next task, the quizStatus utilized in quizStore is continuously keeping track, though

**Review by Mohamad11Dab — APPROVED** [review]
LGTM!

**Pull request merged**
